### ISSUE TITLE
its broken

### ISSUE THREAD

**Issue by nmro97** [Coombaa/TTAutoRecord#47]
![broken](https://github.com/user-attachments/assets/1b4f48bf-1926-47bb-bc8c-3fba6b958580)

**Comment by nmro97** [comment]
i was using the version with firefox however the chrome version is working .

**Comment by jennon** [comment]
Hi, I'm getting this error. Only thing I've done was provide the versions with my cookies

4.1.2 from latest release:
![Capture](https://github.com/user-attachments/assets/7f4cea57-427b-4b5f-a683-22da9acbea13)

4.2.0 main:
![capture420main](https://github.com/user-attachments/assets/51347481-c100-4997-b691-acb313ce59ea)

4.2.0 repo provided by FabLeKebab:
![Capture420fork](https://github.com/user-attachments/assets/1ca564e3-4b4f-4c26-bc6a-1905a9bc7fc9)

**Comment by FabLeKebab** [comment]
Hi, it’s strange, when I was using the official 4.2.0 version, I kept getting errors. Now, I've been using my own link for a few days, and no issues at all—it hasn’t disconnected once. Even before I reset my PC, it was the same with the repo I sent :

![image](https://github.com/user-attachments/assets/8786b15e-187a-409a-98d3-e33e4fb82d9a)

I’ll update if the issue comes back. Did you make sure to install `pip install undetected-chromedriver`
? It doesn’t work on Firefox anymore; everything’s on Chrome now.

**Comment by jennon** [comment]
I did run `pip install -r requirements` prior to running, but just to be sure I ran `pip install undetected-chromedriver` as well. No luck, I'm still getting the same error in my previous message.

**Comment by jean75000** [comment]
@jennon  you have to retrieve cookies on this web page https://www.tiktok.com/live and the tiktok site and your browser must be in English I had errors and I corrected them like this 

since I upgraded to this version I have much less errors in the console and I no longer have No active stream links found and no disconnection for more than 3 weeks my record, I hope it will last

**Comment by jennon** [comment]
@jean75000 no such luck on my end. Browser and Tiktok in English, retrieved cookies as json on that page, but I'm still getting the same error (Element not interactable)

**Comment by FabLeKebab** [comment]
@jean75000 Everything's running smoothly here now! Just need to avoid updating to the new repository, or it'll be a hassle. I struggled to find the original 4.2.0 repository, but now it's working perfectly, everything's running fine.
 
 @jennon It’s frustrating that your issue still isn’t resolved... Plus, there’s really nothing else to do other than what you’ve already done, not even needing to patch the environment like with Stable Diffusion/Rope or others...
 
I think the problem is probably related to the cookies. EditThisCookie has been removed from the Chrome Web Store again. Were you using this extension or another one? I don't think it has a direct impact, but on my end, when I was on version 4.1.2 and EditThisCookie was removed, a similar extension didn't do the job, unlike EditThisCookie, which works really well.

**Comment by jennon** [comment]
@FabLeKebab I'm using Cookie-Editor, which worked until, well, it broke on me. I'll try and see if I can locate EditThisCookie and give it another shot, but for now I'm using a different downloader... which requires a new running instance per tracked room, which is rather unfortunate.

**Comment by FabLeKebab** [comment]
> @FabLeKebab J'utilise Cookie-Editor, qui a fonctionné jusqu'à ce que, eh bien, il me tombe en panne. Je vais essayer de voir si je peux localiser EditThisCookie et lui donner une autre chance, mais pour l'instant j'utilise un autre téléchargeur... qui nécessite une nouvelle instance en cours d'exécution par pièce suivie, ce qui est plutôt malheureux.

I had used that one too, but it didn’t work when it was removed from the store the first time. However, funny coincidence, it’s back now: [(https://chromewebstore.google.com/detail/editthiscookies/hlgpnddmgbhkmilmcnejaibhmoiljhhb)](url). Try this one, hopefully it works this time!

**Comment by raylangivens1** [comment]
Hello guys.

Im a person that tries everything before asking for help. I'm having the same issue or similar than @jennon. I've tried to install python 3 times and downloaded/tried the 3 versions of the programs. In my case, only 4.1 launchs, but it gives lot of errors. I'm using W10 and installing the pip requirements with git bash. 

When I install the requirements in python everything seems to work fine. I've tried to put the chrome in english and Tiktok is in english too. I've copied the cookies with EditThisCookies in chrome.

In my case these are the errors:

`Starting browser..
Exception in thread Thread-3 (main):
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 134, in main
    browser_operations()
    ~~~~~~~~~~~~~~~~~~^^
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 26, in browser_operations
    driver = start_browser()
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 53, in start_browser
    driver = webdriver.Firefox(service=service, options=options)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

2024-11-09 02:24:12,740 - INFO - Starting the program...
Exception in thread Thread-2 (main):
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 196, in main
    driver = start_browser()
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 101, in start_browser
    driver = webdriver.Firefox(service=service, options=options)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

`

Idk if it could be usefull, but the other 2 py doesnt even launch (4.2 and the other one) but if I launch for ex 4.2 with git bash it shows up this errors:

`$ py main.py
Traceback (most recent call last):
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 5, in <modu
le>
    import undetected_chromedriver as uc
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag
es\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag
es\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
`

Hope you could help me, thanks a lot in advance.

**Comment by FabLeKebab** [comment]
> Hello guys.
> 
> Im a person that tries everything before asking for help. I'm having the same issue or similar than @nmro97. I've tried to install python 3 times and downloaded/tried the 3 versions of the programs. In my case, only 4.1 launchs, but it gives lot of errors. I'm using W10 and installing the pip requirements with git bash.
> 
> When I install the requirements in python everything seems to work fine. I've tried to put the chrome in english and Tiktok is in english too. I've copied the cookies with EditThisCookies in chrome.
> 
> In my case these are the errors:
> 
> ```
> Starting browser..
> Exception in thread Thread-3 (main):
> Traceback (most recent call last):
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
>     self.run()
>     ~~~~~~~~^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
>     self._target(*self._args, **self._kwargs)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 134, in main
>     browser_operations()
>     ~~~~~~~~~~~~~~~~~~^^
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 26, in browser_operations
>     driver = start_browser()
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 53, in start_browser
>     driver = webdriver.Firefox(service=service, options=options)
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
>     super().__init__(command_executor=executor, options=options)
>     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
>     self.start_session(capabilities)
>     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
>     response = self.execute(Command.NEW_SESSION, caps)["value"]
>                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
>     self.error_handler.check_response(response)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> 
> 2024-11-09 02:24:12,740 - INFO - Starting the program...
> Exception in thread Thread-2 (main):
> Traceback (most recent call last):
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
>     self.run()
>     ~~~~~~~~^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
>     self._target(*self._args, **self._kwargs)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 196, in main
>     driver = start_browser()
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 101, in start_browser
>     driver = webdriver.Firefox(service=service, options=options)
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
>     super().__init__(command_executor=executor, options=options)
>     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
>     self.start_session(capabilities)
>     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
>     response = self.execute(Command.NEW_SESSION, caps)["value"]
>                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
>     self.error_handler.check_response(response)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> ```
> 
> Idk if it could be usefull, but the other 2 py doesnt even launch (4.2 and the other one) but if I launch for ex 4.2 with git bash it shows up this errors:
> 
> `$ py main.py Traceback (most recent call last): File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 5, in <modu le> import undetected_chromedriver as uc File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\__init__.py", line 44, in <module> from .patcher import IS_POSIX File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\patcher.py", line 4, in <module> from distutils.version import LooseVersion ModuleNotFoundError: No module named 'distutils' `
> 
> Hope you could help me, thanks a lot in advance.

Hello,

I suggest you drop version 4.1.2. It works, but it causes issues in the long run. 
Try this first: ```bash pip install setuptools```

Then, make sure you’re using Python version 3.10.X. I personally use 3.10.11, as newer versions have compatibility issues with certain modules. So, if you haven’t done so already, install Python 3.10 and see if that fixes the problem.

**Comment by raylangivens1** [comment]
> > Hello guys.
> > Im a person that tries everything before asking for help. I'm having the same issue or similar than @nmro97. I've tried to install python 3 times and downloaded/tried the 3 versions of the programs. In my case, only 4.1 launchs, but it gives lot of errors. I'm using W10 and installing the pip requirements with git bash.
> > When I install the requirements in python everything seems to work fine. I've tried to put the chrome in english and Tiktok is in english too. I've copied the cookies with EditThisCookies in chrome.
> > In my case these are the errors:
> > ```
> > Starting browser..
> > Exception in thread Thread-3 (main):
> > Traceback (most recent call last):
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
> >     self.run()
> >     ~~~~~~~~^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
> >     self._target(*self._args, **self._kwargs)
> >     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 134, in main
> >     browser_operations()
> >     ~~~~~~~~~~~~~~~~~~^^
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 26, in browser_operations
> >     driver = start_browser()
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 53, in start_browser
> >     driver = webdriver.Firefox(service=service, options=options)
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
> >     super().__init__(command_executor=executor, options=options)
> >     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
> >     self.start_session(capabilities)
> >     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
> >     response = self.execute(Command.NEW_SESSION, caps)["value"]
> >                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
> >     self.error_handler.check_response(response)
> >     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> > 
> > 2024-11-09 02:24:12,740 - INFO - Starting the program...
> > Exception in thread Thread-2 (main):
> > Traceback (most recent call last):
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
> >     self.run()
> >     ~~~~~~~~^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
> >     self._target(*self._args, **self._kwargs)
> >     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 196, in main
> >     driver = start_browser()
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 101, in start_browser
> >     driver = webdriver.Firefox(service=service, options=options)
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
> >     super().__init__(command_executor=executor, options=options)
> >     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
> >     self.start_session(capabilities)
> >     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
> >     response = self.execute(Command.NEW_SESSION, caps)["value"]
> >                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
> >     self.error_handler.check_response(response)
> >     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Idk if it could be usefull, but the other 2 py doesnt even launch (4.2 and the other one) but if I launch for ex 4.2 with git bash it shows up this errors:
> > `$ py main.py Traceback (most recent call last): File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 5, in <modu le> import undetected_chromedriver as uc File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\__init__.py", line 44, in <module> from .patcher import IS_POSIX File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\patcher.py", line 4, in <module> from distutils.version import LooseVersion ModuleNotFoundError: No module named 'distutils' `
> > Hope you could help me, thanks a lot in advance.
> 
> Hello,
> 
> I suggest you drop version 4.1.2. It works, but it causes issues in the long run. Try this first: `pip install setuptools`
> 
> Then, make sure you’re using Python version 3.10.X. I personally use 3.10.11, as newer versions have compatibility issues with certain modules. So, if you haven’t done so already, install Python 3.10 and see if that fixes the problem.

Thanks @FabLeKebab !

Its almost there with 4.2. Now it tries to open chrome. First time i've tried it has worked but session was not logged in, and was retrying everytime. After that, it gives me this error everytime and get all chrome windows closed.

```
$ py main.py
2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
data\roaming\undetected_chromedriver\undetected_chromedriver.exe
Traceback (most recent call last):
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
ule>
    copy_chromedriver_executable()
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
_chromedriver_executable
    shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
 line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
TAutoRecord-4.2.0\\session\\chromedriver_1.exe'

```

I'm using EditThisCookie addon for chrome to get the cookies, but im not sure if its working fine because it gives the information like without page breaks, like all followed. I've used the firefox addon of EditThisCookie and there it works perfect tho.

**Comment by FabLeKebab** [comment]
> > > Hello guys.
> > > Im a person that tries everything before asking for help. I'm having the same issue or similar than @nmro97. I've tried to install python 3 times and downloaded/tried the 3 versions of the programs. In my case, only 4.1 launchs, but it gives lot of errors. I'm using W10 and installing the pip requirements with git bash.
> > > When I install the requirements in python everything seems to work fine. I've tried to put the chrome in english and Tiktok is in english too. I've copied the cookies with EditThisCookies in chrome.
> > > In my case these are the errors:
> > > ```
> > > Starting browser..
> > > Exception in thread Thread-3 (main):
> > > Traceback (most recent call last):
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
> > >     self.run()
> > >     ~~~~~~~~^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
> > >     self._target(*self._args, **self._kwargs)
> > >     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 134, in main
> > >     browser_operations()
> > >     ~~~~~~~~~~~~~~~~~~^^
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 26, in browser_operations
> > >     driver = start_browser()
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\user_check.py", line 53, in start_browser
> > >     driver = webdriver.Firefox(service=service, options=options)
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
> > >     super().__init__(command_executor=executor, options=options)
> > >     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
> > >     self.start_session(capabilities)
> > >     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
> > >     response = self.execute(Command.NEW_SESSION, caps)["value"]
> > >                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
> > >     self.error_handler.check_response(response)
> > >     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
> > >     raise exception_class(message, screen, stacktrace)
> > > selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> > > 
> > > 2024-11-09 02:24:12,740 - INFO - Starting the program...
> > > Exception in thread Thread-2 (main):
> > > Traceback (most recent call last):
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
> > >     self.run()
> > >     ~~~~~~~~^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
> > >     self._target(*self._args, **self._kwargs)
> > >     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 196, in main
> > >     driver = start_browser()
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-main\modules\get_stream_link.py", line 101, in start_browser
> > >     driver = webdriver.Firefox(service=service, options=options)
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 71, in __init__
> > >     super().__init__(command_executor=executor, options=options)
> > >     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
> > >     self.start_session(capabilities)
> > >     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
> > >     response = self.execute(Command.NEW_SESSION, caps)["value"]
> > >                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
> > >     self.error_handler.check_response(response)
> > >     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
> > >     raise exception_class(message, screen, stacktrace)
> > > selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Idk if it could be usefull, but the other 2 py doesnt even launch (4.2 and the other one) but if I launch for ex 4.2 with git bash it shows up this errors:
> > > `$ py main.py Traceback (most recent call last): File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 5, in <modu le> import undetected_chromedriver as uc File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\__init__.py", line 44, in <module> from .patcher import IS_POSIX File "C:\Users\usuario\AppData\Local\Programs\Python\Python313\Lib\site-packag es\undetected_chromedriver\patcher.py", line 4, in <module> from distutils.version import LooseVersion ModuleNotFoundError: No module named 'distutils' `
> > > Hope you could help me, thanks a lot in advance.
> > 
> > 
> > Hello,
> > I suggest you drop version 4.1.2. It works, but it causes issues in the long run. Try this first: `pip install setuptools`
> > Then, make sure you’re using Python version 3.10.X. I personally use 3.10.11, as newer versions have compatibility issues with certain modules. So, if you haven’t done so already, install Python 3.10 and see if that fixes the problem.
> 
> Thanks @FabLeKebab !
> 
> Its almost there with 4.2. Now it tries to open chrome. First time i've tried it has worked but session was not logged in, and was retrying everytime. After that, it gives me this error everytime and get all chrome windows closed.
> 
> ```
> $ py main.py
> 2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
> data\roaming\undetected_chromedriver\undetected_chromedriver.exe
> Traceback (most recent call last):
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
> ule>
>     copy_chromedriver_executable()
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
> _chromedriver_executable
>     shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
>  line 256, in copyfile
>     with open(dst, 'wb') as fdst:
> PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
> TAutoRecord-4.2.0\\session\\chromedriver_1.exe'
> ```
> 
> I'm using EditThisCookie addon for chrome to get the cookies, but im not sure if its working fine because it gives the information like without page breaks, like all followed. I've used the firefox addon of EditThisCookie and there it works perfect tho.

I didn’t know that this extension was available on Firefox either; they must have added it recently. Are all the live downloads working fine for you now? If so, that’s great! If not, feel free to reach out for help :)

**Comment by raylangivens1** [comment]
> > > > 
> I didn’t know that this extension was available on Firefox either; they must have added it recently. Are all the live downloads working fine for you now? If so, that’s great! If not, feel free to reach out for help :)

Hello!

Nono its not working due to that last errors. I copy the code here again. Now this is working with chrome since its 4.2 version. Im using ur same pythong version rn (3.10.11 - w10 64 bits)

`$ py main.py
2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
data\roaming\undetected_chromedriver\undetected_chromedriver.exe
Traceback (most recent call last):
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
ule>
    copy_chromedriver_executable()
  File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
_chromedriver_executable
    shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
 line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
TAutoRecord-4.2.0\\session\\chromedriver_1.exe'`

**Comment by FabLeKebab** [comment]
> > > > > 
> > I didn’t know that this extension was available on Firefox either; they must have added it recently. Are all the live downloads working fine for you now? If so, that’s great! If not, feel free to reach out for help :)
> 
> Hello!
> 
> Nono its not working due to that last errors. I copy the code here again. Now this is trying to use chrome since its 4.2 version. Im using ur same pythong version rn (3.10.11 - w10 64 bits)
> 
> ```
> $ py main.py
> 2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
> data\roaming\undetected_chromedriver\undetected_chromedriver.exe
> Traceback (most recent call last):
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
> ule>
>     copy_chromedriver_executable()
>   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
> _chromedriver_executable
>     shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
>   File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
>  line 256, in copyfile
>     with open(dst, 'wb') as fdst:
> PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
> TAutoRecord-4.2.0\\session\\chromedriver_1.exe'
> ```
> 

Hey,

It looks like the error might be because the script doesn’t have permission to copy chromedriver_1.exe into the session folder (at G:\PF\Capturas
TT\Programa\TTAutoRecord-4.2.0\session)

Try these steps:

1. Check if the session folder exists

2. Make sure you have read and write permissions for it

3. Restart your computer to ensure no other program is using the file

Take a closer look at the error "PermissionError: [Errno 13] Permission denied". It might give you more insight. It’s just a lead, but worth a try!

**Comment by raylangivens1** [comment]
> > > > > >
> > > 
> > > 
> > > I didn’t know that this extension was available on Firefox either; they must have added it recently. Are all the live downloads working fine for you now? If so, that’s great! If not, feel free to reach out for help :)
> > 
> > 
> > Hello!
> > Nono its not working due to that last errors. I copy the code here again. Now this is trying to use chrome since its 4.2 version. Im using ur same pythong version rn (3.10.11 - w10 64 bits)
> > ```
> > $ py main.py
> > 2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
> > data\roaming\undetected_chromedriver\undetected_chromedriver.exe
> > Traceback (most recent call last):
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
> > ule>
> >     copy_chromedriver_executable()
> >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
> > _chromedriver_executable
> >     shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
> >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
> >  line 256, in copyfile
> >     with open(dst, 'wb') as fdst:
> > PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
> > TAutoRecord-4.2.0\\session\\chromedriver_1.exe'
> > ```
> 
> Hey,
> 
> It looks like the error might be because the script doesn’t have permission to copy chromedriver_1.exe into the session folder (at G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\session)
> 
> Try these steps:
> 
> 1. Check if the session folder exists
> 2. Make sure you have read and write permissions for it
> 3. Restart your computer to ensure no other program is using the file
> 
> Take a closer look at the error "PermissionError: [Errno 13] Permission denied". It might give you more insight. It’s just a lead, but worth a try!

I've just realized that the box: Read only was enabled, but not in that folder only. I've it enabled in all the folders of my pc. If I try to unbox it, it asks about subfolders and when I acept it loads like 5 seconds but nothing happens. If I check properties again it keeps the read only box LOL This may be the problem

![problem1](https://github.com/user-attachments/assets/26f1daf2-0add-4a09-b895-6f6265e362d8)

**Comment by FabLeKebab** [comment]
> > > > > > >
> > > > 
> > > > 
> > > > Je ne savais pas non plus que cette extension était disponible sur Firefox ; ils ont dû l'ajouter récemment. Est-ce que tous les téléchargements en direct fonctionnent correctement pour vous maintenant ? Si c'est le cas, c'est super ! Sinon, n'hésitez pas à demander de l'aide :)
> > > 
> > > 
> > > Bonjour! 
> > > Non non, cela ne fonctionne pas à cause de ces dernières erreurs. Je copie à nouveau le code ici. Maintenant, cela essaie d'utiliser Chrome depuis sa version 4.2. J'utilise votre même version Pythong rn (3.10.11 - w10 64 bits) 
> > > ```
> > > $ py main.py
> > > 2024-11-09 17:25:44,016 - INFO - patching driver executable C:\Users\usuario\app
> > > data\roaming\undetected_chromedriver\undetected_chromedriver.exe
> > > Traceback (most recent call last):
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 98, in <mod
> > > ule>
> > >     copy_chromedriver_executable()
> > >   File "G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\main.py", line 39, in copy
> > > _chromedriver_executable
> > >     shutil.copyfile(original_driver_path, CHROMEDRIVER_PATH_1)
> > >   File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py",
> > >  line 256, in copyfile
> > >     with open(dst, 'wb') as fdst:
> > > PermissionError: [Errno 13] Permission denied: 'G:\\PF\\Capturas TT\\Programa\\T
> > > TAutoRecord-4.2.0\\session\\chromedriver_1.exe'
> > > ```
> > 
> > 
> > Hé, 
> > Il semble que l'erreur soit due au fait que le script n'est pas autorisé à copier chromedriver_1.exe dans le dossier de session (dans G:\PF\Capturas TT\Programa\TTAutoRecord-4.2.0\session). 
> > Essayez ces étapes : 
> > 
> > 1. Vérifiez si le dossier de session existe
> > 2. Assurez-vous que vous disposez des autorisations de lecture et d'écriture pour celui-ci
> > 3. Redémarrez votre ordinateur pour vous assurer qu'aucun autre programme n'utilise le fichier
> > 
> > Examinez de plus près l'erreur « PermissionError : [Errno 13] Autorisation refusée ». Cela pourrait vous donner plus d'informations. Ce n'est qu'une piste, mais ça vaut le coup d'essayer !
> 
> Je viens de réaliser que la case : Lecture seule était activée, mais pas uniquement dans ce dossier. Je l'ai activé dans tous les dossiers de mon PC. Si j'essaie de le déballer, il pose des questions sur les sous-dossiers et lorsque j'accepte, il se charge environ 5 secondes mais rien ne se passe. Si je vérifie à nouveau les propriétés, la boîte de lecture seule reste MDR. Cela peut être le problème.
> 
> ![problème 1](https://private-user-images.githubusercontent.com/30196442/384734475-26f1daf2-0add-4a09-b895-6f6265e362d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTcxNjIsIm5iZiI6MTczMTMxNjg2MiwicGF0aCI6Ii8zMDE5NjQ0Mi8zODQ3MzQ0NzUtMjZmMWRhZjItMGFkZC00YTA5LWI4OTUtNmY2MjY1ZTM2MmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA5MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOTNkYzAzMjFiOTMwNjAyMGJhMmJhNDdlNDMyODgwZTU1MWMwMDNhYmUzNTU1ZjI5MTRjODVlOTc3ZjZiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PLYWaWCygy_5ZXn1yVzFH4DMj6LNiu0KvOhLhGK0H38)

![image](https://github.com/user-attachments/assets/b41650f5-89c5-4be6-be1a-f7c3c9154a8e)
Well, now it's my turn to have problems hahaha...

Hey @jean75000 Could you share the repo you were using before TTAutoRecord started bugging? I can’t find any other alternatives. Thanks in advance!

**Comment by FabLeKebab** [comment]
Update : I finally reset my PC and now it's working. It's a bit drastic, but at least it's working. It's a little strange, but oh well...
With this repository : https://github.com/Coombaa/TTAutoRecord/tree/e36ee6281a702d62f0b02869e4dc7758b016a7e4

@raylangivens1 If your PC hasn’t been reset in a while and is starting to have issues, I recommend doing a reset, especially if you want to use TTAutoRecord. It’s a bit of a drastic step, but it really worked well for me. Since then, I’ve been more careful about what I install because it was strange: everything was fine until it suddenly crashed, and after the reset, everything went back to normal.

That said, you don’t necessarily need to reset everything if the problem is mainly related to writing. You could also try partitioning your hard drive if possible. For example, one partition for Windows and another for software, games, etc. This might help you better manage space without needing to reinstall everything.

Personally, this is how I organize things, but of course, everyone can do it however they prefer!
![image](https://github.com/user-attachments/assets/43ab10a0-f24d-42ce-a670-9f556005347f)

**Comment by jean75000** [comment]
I have a same problem...
![image](https://github.com/user-attachments/assets/31e6ea6a-6f9e-4107-9889-b827330f7fbf)

**Comment by FabLeKebab** [comment]
> > > I have a same problem... ![image](https://private-user-images.githubusercontent.com/168682836/385013897-31e6ea6a-6f9e-4107-9889-b827330f7fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDc4MzQsIm5iZiI6MTczMTM0NzUzNCwicGF0aCI6Ii8xNjg2ODI4MzYvMzg1MDEzODk3LTMxZTZlYTZhLTZmOWUtNDEwNy05ODg5LWI4MjczMzBmN2ZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNzUyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjllMDUyOWU1MjMzOTBlZmIwMWRkMTBmM2U3ZGViYjhhMGE1OGE2ZDg3OGRjZjU5YTQ1Zjc3NzA5NTE2Mzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pebLZrr98Y-E2BtADxkSV3TXJXkZlIYyCTxNZAhFcp0)
> > 
> > 
> > It's crazy, I don't have this problem anymore, I just did a full reset. I wonder what's wrong, it's really strange. I was actually about to edit my message to say that the "Cookie Editor" extension (link here: https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm) can replace EditThisCookie. The other one seems like a "scam" and doesn't even redirect to GitHub, but to a fake page with no clickable links...
> > ![image](https://private-user-images.githubusercontent.com/109556581/385018666-6b485345-714f-467d-90ec-85aa31ccee51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDgwNjksIm5iZiI6MTczMTM0Nzc2OSwicGF0aCI6Ii8xMDk1NTY1ODEvMzg1MDE4NjY2LTZiNDg1MzQ1LTcxNGYtNDY3ZC05MGVjLTg1YWEzMWNjZWU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNzU2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWFmNWJiOWYzOTdjMTRhNDExZmYyMzE3YTkxYzY3ZTYzODYyODJjMzMxZmQxOGU2YWE4N2FkYzIyZGEyMWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wGUOxJ9XyqQ-J2wTZSppYmUX-e9MqEgeBNKMcLzbSlA)
> 
> This is just a development branch, its not finished.
> 
> The elements are not clickable because the cookie banner is in the way

The EditThisCookie update from November 8th was causing issues with line blocks. However, the version I just installed works like ETC. As for the 4.2.0 branch, it works fine, at least the one I’m using and that everyone here is using (I think). If a problem arises, which repository should we revert to ?

**Comment by jean75000** [comment]
It doesn't work any better with Cookie Editor and I can't be bothered to reinstall everything...

**Comment by jean75000** [comment]
I don't understand it worked for more than 20 days and suddenly it crashes I tried everything I still have the problem

**Comment by jean75000** [comment]
I reinstalled everything and I have the same problem...
